---
title: "week 5"
output: html_document
date: "2024-02-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
url = r"(https://raw.githubusercontent.com/KanizSanzida/DATA607/main/Flightdata.csv)"
suppressMessages(
df <- read_csv(url, skip_empty_rows = TRUE, show_col_types = FALSE)[-3,] # Skip_empty_rows does not work here and I'm not sure why, as we can see the third row is empty and gets converted to NAs as if skip_empty_rows = FALSE
)
names(df)[1:2] <- c("Airline", "Delay Status")
df
```

```{r}
df2 <- df |>
  fill(Airline) |>
  pivot_longer(cols=3:7,names_to= "City",values_to = "Count")
glimpse(df2)
```

```{r}
df2 |>
  group_by(Airline, `Delay Status`) |>
  summarize("Flights" = sum(Count), .groups= "drop_last") |>
  mutate("Proportion of Flights" = Flights/sum(Flights)) |>
  knitr::kable()
```

```{r}
ggplot(df2, aes(x=Airline,y=Count,fill = `Delay Status`)) +
  geom_bar(stat="identity", position = position_fill(reverse= TRUE)) +
  facet_wrap(~City) +
  labs(title = "Flight Delays Per City", y = "Proportion of Flights") +
  theme(legend.position = c(.85,.25), plot.title = element_text(hjust = 0.5))
```

